public enum Jante {
    TREIZE_POUCES , QUATORZE_POUCES, QUINZE_POUCES , SEIZE_POUCES , DIX_SEPT_POUCES , DIX_HUIT_POUCES , DIX_NEUF_POUCES
    , VINGT_POUCES, VINGT_UN_POUCES, VINGT_DEUX_POUCES, VINGT_TROIS_POUCES
}
